config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  get    '/backstage', to: 'backstage#index'

  get    'pipes/export', to: 'pipes#export'

  resources :sessions
  resources :users
  resources :pipes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pipe.rb
class Pipe < ApplicationRecord
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: Rails.configuration.valid_email_regex }

  before_create :generate_new_token

  # Generates a new token.
  def generate_new_token
    self.token = SecureRandom.urlsafe_base64
  end


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |pipe|
        csv << pipe.attributes.values_at(*column_names)
      end
    end
  end



end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  before_save { self.email = email.downcase }
  validates :username,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: Rails.configuration.valid_email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

   # Confirms a logged-in user.
   def logged_in_user
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
   end
end

app/controllers/backstage_controller.rb
class BackstageController < ApplicationController
  before_action :logged_in_user
  def index
    @pipes = Pipe.paginate(page: params[:page])
  end
end

app/controllers/pipes_controller.rb
class PipesController < ApplicationController
  before_action :logged_in_user, only: [:index, :update, :edit, :destroy, :show]

  def new
    @pipe = Pipe.new
  end

  def create
    @pipe = Pipe.new(pipe_params)
    if @pipe.save
      flash[:success] = "Pipeline created!"
      render template: "pipes/ok"
    else
      redirect_to root_url
    end
  end

  def edit
    @pipe = Pipe.find(params[:id])
  end

  def update
    @pipe = Pipe.find(params[:id])
    if @pipe.update_attributes(pipe_params)
      flash[:success] = "Pipe updated"
      redirect_to @pipe
    else
      render 'edit'
    end
  end

  def show
    @pipe = Pipe.find(params[:id])
  end

  def destroy
    @pipe = Pipe.find(params[:id])
    @pipe.destroy
    redirect_to backstage_url
  end

  def index
    @pipes = Pipe.paginate(page: params[:page])
  end

  def export
    @pipes = Pipe.all
    respond_to do |format|
      format.csv { send_data @pipes.to_csv }
    end
  end

  private

    def pipe_params
      params.require(:pipe).permit(:email, :description, :status, :ticket, :link,
                                   :groups, :success, :timeframe, :start, :urgency,
                                   :budget, :funding, :additional_funding)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      params[:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to backstage_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def new
    if logged_in?
      redirect_to backstage_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  	if logged_in?
      redirect_to backstage_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :this_user

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password,
                                   :password_confirmation)
    end

    # Confirms the correct user.
    def this_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backstage_helper.rb
module BackstageHelper
end

app/helpers/pipes_helper.rb
module PipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
 def log_out
   session.delete(:user_id)
   @current_user = nil
 end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/backstage/index.html.haml
- provide(:title, "Backstage")
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Pipelines
    / /.col-lg-12
    / /.row
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          Showing pipelines
        / /.panel-heading
        .panel-body
          %table#dataTables-example.table.table-striped.table-bordered.table-hover{:width => "100%"}
            %thead
              %tr
                %th Email
                %th Description
                %th Problem
                %th Trac Ticket
                %th Link
                %th Groups
                %th Success
                %th Timeframe
                %th Start date
                %th Urgency
                %th Budget
                %th Funding information
                %th Additional funding information
                %th Edit
                %th Delete
            %tbody
              = render @pipes
        = will_paginate @pipes
    / /.col-lg-12
  / /.row
/ /#page-wrapper

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pipeline
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  #wrapper
    / Navigation
    %nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
      .navbar-header
        = image_tag( 'Color.png')
        %a.navbar-brand{:href => "/backstage"} Grant Pipeline
      / /.navbar-header
      %ul.nav.navbar-top-links.navbar-right
        - if logged_in?
          %li.btn.btn-danger
            #{link_to 'logout', logout_path(current_user)}
          %li.btn.btn-primary
            #{link_to 'profile', user_path(current_user)}
          %li.btn.btn-primary
            #{link_to 'backstage', backstage_url}
          %li.btn.btn-primary
            #{link_to "Export to CSV", pipes_export_path(format: "csv")}

      / /.navbar-top-links
      .navbar-default.sidebar{:role => "navigation"}
        .sidebar-nav.navbar-collapse
          %ul#side-menu.nav
            %li

        / /.sidebar-collapse
      / /.navbar-static-side
    = yield

app/views/pipes/_form.html.haml
= form_for @pipe do |f|
  /= render "form_errors", resource: pipe
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :email, "Email (please add an email address so we can get back to you)"
        .col-lg-6
          = f.text_field :email
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :description, "In a sentence or two, briefly describe this proposal."
        .col-lg-6
          = f.text_area :description
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :status, "Briefly, what problem(s) are you trying to solve, and how do you intend to do so?"
        .col-lg-6
          = f.text_area :status
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :ticket, "Feel free to link to a Trac ticket here."
        .col-lg-6
          = f.text_field :ticket
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :link, "Feel free to link to an external resource here."
        .col-lg-6
          = f.text_field :link
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :groups, "Who/what groups will benefit from this proposal?"
        .col-lg-6
          = f.text_area :groups
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :success, "How will you measure this proposal's success?"
        .col-lg-6
          = f.text_area :success
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :timeframe, "What is the timeframe for completion of the work in this proposal?"
        .col-lg-6
          = f.text_field :timeframe
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :start, "What is this proposal’s approximate start date?"
        .col-lg-6
          = date_select("pipe", "start", selected: Date.today)
  %fieldset
    .radiobox
      .row
        .col-lg-6
          = label_tag :urgency, "On a scale of 1 (Highest) to 5 (Lowest), how urgent is this proposal?"
        .col-lg-6
          .radios
            - (1..5).to_a.each do |u|
              .button-radio
                = label_tag :u, u.to_s
                = f.radio_button(:urgency, u)
  %fieldset
    .radiobox
      .row
        .col-lg-6
          = label_tag :budget, "What is the approximate budget of this proposal?"
        .col-lg-6
          .radios
            .button-radio
              = label_tag :budget, "< $20,000"
              = f.radio_button(:budget, "< $20,000")
            .button-radio
              = label_tag :budget, "$20,001 - $50,000"
              = f.radio_button(:budget, "$20,001 - $50,000")
            .button-radio            
              = label_tag :budget, "$50,001 - $100,000"
              = f.radio_button(:budget, "$50,001 - $100,000")
            .button-radio
              = label_tag :budget, "$100,001 - $250,000"
              = f.radio_button(:budget, "$100,001 - $250,000")
            .button-radio            
              = label_tag :budget, "$250,000+"
              = f.radio_button(:budget, "$250,000+")
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :funding, "Have we ever received funding for this work, or similar work, in the past? If so, from where and when? Do you think it would be possible to receive additional support from this same funder?"
        .col-lg-6
          = f.text_area :funding
  %fieldset
    .form-group
      .row
        .col-lg-6
          = label_tag :additional_funding, "Are there other funders you have spoken with about this proposal? Anyone we should follow up with? Anyone we should avoid?"
        .col-lg-6
          = f.text_area :additional_funding
  %p
    Thanks for taking the time to give us this data. Someone will follow up with you when we begin to work on your proposal. If you have any questions, please email grants [at] torproject [dot] org.

  .actions= f.submit "Send this", class: 'btn btn-lg btn-success btn-block'

app/views/pipes/_pipe.html.haml
%tr.odd
  %td
    = pipe.email
  %td
    = pipe.description
  %td
    = pipe.status
  %td
    = pipe.ticket
  %td
    = pipe.link
  %td
    = pipe.groups
  %td
    = pipe.success
  %td
    = pipe.timeframe
  %td
    = pipe.start
  %td
    = pipe.urgency
  %td
    = pipe.budget
  %td
    = pipe.funding
  %td
    = pipe.additional_funding
  %td
    #{link_to 'edit', edit_pipe_url(pipe)}
  %td
    #{link_to 'delete', pipe_url(pipe), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'}

app/views/pipes/edit.html.haml
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Edit a grant proposal
    / /.col-lg-12
  / /.row
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          You are about to edit this grant. Maybe you wanted to consult with the sender first?
        .panel-body
          .row
            .col-lg-8
              = render 'form', pipe: @pipe
          .row
            .col-lg-8
              = link_to 'delete', pipe_url(@pipe), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'

            / /.col-lg-8 (nested)
          / /.row (nested)
        / /.panel-body
      / /.panel
    / /.col-lg-12
  / /.row
/ /#page-wrapper

app/views/pipes/new.html.haml
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Send a new grant proposal
    / /.col-lg-12
  / /.row
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          Please give us more information about your proposal. This will allow the grants (and the proposals!) to move faster. Please answer as many questions as you can.
        .panel-body
          .row
            .col-lg-12
              = render 'form', pipe: @pipe

            / /.col-lg-8 (nested)
          / /.row (nested)
        / /.panel-body
      / /.panel
    / /.col-lg-12
  / /.row
/ /#page-wrapper

app/views/pipes/ok.html.haml
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Your proposal has been sent.
    / /.col-lg-12
  / /.row
  .row
    .col-lg-12
      %p
        Please note the following token if you'd like to refer to it later:
      %p
        = @pipe.token
      %p
        %a.btn.btn-success{:href => "/"} Continue

app/views/pipes/show.html.haml
- provide(:title, "pipe: #{@pipe.id}")
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header pipe: #{@pipe.id} from: #{@pipe.email}
    / /.col-lg-12
    / /.row
  .row
    .col-lg-12
      .panel.panel-default
        .panel-heading
          pipe: #{@pipe.id}
        / /.panel-heading
        .panel-body
          %table#dataTables-example.table.table-striped.table-bordered.table-hover{:width => "100%"}
            %thead
              %tr
                %th Email
                %th Description
                %th Problem
                %th Trac Ticket
                %th Link
                %th Groups
                %th Success
                %th Timeframe
                %th Start date
                %th Urgency
                %th Budget
                %th Funding information
                %th Additional funding information
                %th Edit
            %tbody
              %td
                = @pipe.email
              %td
                = @pipe.description
              %td
                = @pipe.status
              %td
                = @pipe.ticket
              %td
                = @pipe.link
              %td
                = @pipe.groups
              %td
                = @pipe.success
              %td
                = @pipe.timeframe
              %td
                = @pipe.start
              %td
                = @pipe.urgency
              %td
                = @pipe.budget
              %td
                = @pipe.funding
              %td
                = @pipe.additional_funding
              %td
                #{link_to 'edit', edit_pipe_url(@pipe)}

    / /.col-lg-12
  / /.row
/ /#page-wrapper%tr.odd

app/views/users/_form.html.haml
= form_for @user do |f|
  /= render "form_errors", resource: pipe
  %fieldset
    .form-group
      .row
        .col-md-4
          = label_tag :password, "Password"
        .col-md-8
          = f.password_field :password
      .row
        %hr/
      .row
        .col-md-4
          = label_tag :password_confirmation, "Password confirmation"
        .col-md-8
          = f.password_field :password_confirmation
      .row
        %hr/
      .row
        .col-md-4
          .actions= f.submit "Send this", class: 'btn btn-lg btn-success btn-block'
        

app/views/users/edit.html.haml
#page-wrapper
  .row
    .col-lg-12
      %h1.page-header Edit Profile
  .row
    .col-md-12
      .panel.panel-default
      .panel-heading
        %h3
          Editing your profile
      / /.panel-heading
      .panel-body
        .row
          .col-md-12
            = render 'form', user: @user

app/views/users/show.html.haml
#page-wrapper
  .row
    .col-lg-12
      .row
        %p
          = @user.username
      .row
        %p
          = @user.email
      .row
        .col-md-2
        .col-md-2
          #{link_to 'change your password', edit_user_url(@user), class: 'btn btn-lg btn-danger btn-block'}          